### ISSUE TITLE
can not import any modules

### ISSUE THREAD

**Issue by cogmeta** [kubemq-io/kubemq-Python#1]
python infra/kubemq-Python/examples/event-sender.py 
Traceback (most recent call last):
  File "infra/kubemq-Python/examples/event-sender.py", line 3, in <module>
    from kubemq.events.lowlevel.event import Event
ImportError: No module named events.lowlevel.event

**Comment by cogmeta** [comment]
kubemq-1.0.1-py2.7.egg is empty.

**Comment by cogmeta** [comment]
events is missing from requirements.txt

**Comment by ET-CS** [comment]
`setup.py` updated with the sub‑packages and requirements. please try to `pull` and retry again

**Comment by cogmeta** [comment]
Resolved. perfect! thanks.
