### ISSUE TITLE
Error connecting from windows client - works fine with mac and linux

### ISSUE THREAD

**Issue by cogmeta** [kubemq-io/kubemq-Python#2]
C:\Users\sas\kubemq-Python>python event-subscriber.py
Subscribing to event on channel example
Press 'Enter' to stop the application...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\sas\kubemq-Python\kubemq\events\subscriber.py", line 41, in subscribe_to_event
    event_receive = call.next()
  File "C:\Python27\lib\site-packages\grpc\_channel.py", line 366, in next
    return self._next()
  File "C:\Python27\lib\site-packages\grpc\_channel.py", line 357, in _next
    raise self
_Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Trying to connect an http1.x server"
        debug_error_string = "{"created":"@1548680473.025000000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"Trying to connect an http1.x server","grpc_status":14}"
>

**Comment by Ido-Sheffer** [comment]
Hi, are you using a local KubeMQ setup or is it running on kube?

**Comment by cogmeta** [comment]
It is local setup. Could be grpc or some other issue. We are trying to resolve it and update you soon. Thanks.

**Comment by cogmeta** [comment]
Works! our apologies. closing..

**Comment by Ido-Sheffer** [comment]
Good to hear about it.
What was it? is there something we can do to make installation clear?

**Comment by cogmeta** [comment]
It was just firewall/proxy issue. Nothing to do with kubemq or grpc.
