### ISSUE TITLE
c/c++ library

### ISSUE THREAD

**Issue by cogmeta** [kubemq-io/kubemq-Python#3]
any plans to release c/c++ library? Any pointers on how to build one ?

**Comment by Ido-Sheffer** [comment]
would recommend using the go sdk (https://github.com/kubemq-io/kubemq-go) as template to implement proto grpc (https://github.com/kubemq-io/protobuf/blob/master/kubemq.proto)
https://grpc.io/docs/quickstart/cpp/.
