### ISSUE TITLE
Not able to delete a channel

### ISSUE THREAD

**Issue by celebgnu** [kubemq-io/kubemq-Python#57]
Hello,

I am looking for a mechanism to delete a channel(A Queue or a Event).

Regards,
Shrikant.

**Comment by kubemq** [comment]
Hi,
No need,
Channels are auto deleted if not used over a day.
You can set it up on the configuration

**Comment by celebgnu** [comment]
Can you please elaborate on which section in config file and keys details, Any documentation will also be very helpful.

**Comment by kubemq** [comment]
Contact us on the slack channel
