### ISSUE TITLE
Release 1.0.2 is missing

### ISSUE THREAD

**Issue by torquerrr** [kubemq-io/kubemq-Python#6]
Release 1.0.2 is missing from PyPi.org as it was deleted.
PyPi should contain all releases.

**Comment by andi23rosca** [comment]
Had the same problem, had to install 1.0.4. Beware, the subscribe_to_events is broken from one version to the next, you need to supply and extra method to handle errors

**Comment by torquerrr** [comment]
@andi23rosca Thanks for the warning, that's why I decided to stick to particular commit hash from v.1.0.2.

**Comment by eitam-ring** [comment]
@torquerrr Thanks for the notice
1.0.2 was reuploaded to pip.
