### ISSUE TITLE
Support for Python3.8 on Windows

### ISSUE THREAD

**Issue by orryun** [kubemq-io/kubemq-Python#8]
Hi, 
Kubemq python package depends on grpcio==1.17.1.
However, grpcio does not offer a whl file for python3.8 on this version.

I manually updated the dependency to a newer version and it works just as good. (I used latest version, as of today it is 1.27.2).

Please update this dependency.. compiling grpcio is tricky in windows because it relies on pthread.h

Thanks!

**Comment by eitam-ring** [comment]
Hi,
@orryun 
Please check version 1.1.0
Released today, address this issue
