### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by imarinmed** [kubemq-io/kubemq-Python#9]
In my current project, I am using `kubemq` as part of a networking internal library which is used by several services, including one for machine learning purposes. However, when trying to tie everything together, `kubemq` is unable to play proper with the `tensorflow`package:

```
[SolverProblemError]
Because kubemq (1.1.0) depends on protobuf (3.6.1)
 and no versions of kubemq match >1.1.0,<2.0.0, kubemq (>=1.1.0,<2.0.0) requires protobuf (3.6.1).
So, because <my-project> depends on both kubemq (^1.1.0) and protobuf (^3.13.0), version solving failed.
```

As poetry indicates, this is just a dependency problem: kubemq points to an outdated protobuf version, while the tensorflow library within my project points to the most updated one (3.13.0). 

## Proposal: how to fix
This issue seems simple enough :) Just updating the dependencies should fix the problem. It is also interesting to mention that protobuf is reaching 4.0.0 in its next version, so maybe kubemq-python could start using poetry to better track and manage these issues in the future :)

**Comment by eitamring** [comment]
Hey @imarinmed 
Thanks for the notice(both on proto and dependencies )
will get to it soon and update you.

**Comment by eitam-ring** [comment]
Hi @imarinmed ,
Thanks for the notice, we will look into it and update you.

**Comment by eitam-ring** [comment]
Hi @imarinmed 
This issue was addressed in the latest release

**Comment by imarinmed** [comment]
Hi, @eitam-ring, thank you so much! We'll now re-implement it right away (to go around this problem for short-term, we made an internal fork and made specific changes to address it). 

Also, would you consider external contributions to this project from us?

**Comment by eitam-ring** [comment]
Hi, @imarinmed 
No problem,
Regarding the external contributions,
Yes, we do consider and accept, 
Just create a fork, and arrange a pull request, once it been approved we will marge it to the master.

**Comment by eitam-ring** [comment]
Closing since the issue has been resolved,
If needed feel free to open a new issue @imarinmed .
